### PR TITLE
Feature/bounty client tests

### PR DESCRIPTION
**Pull request by pgrzesik**
Increased test coverage from 44 to 50%, by testing parts of client helpers and bounty client. 

I also have a suggestion, to break up tests into separate modules, but I didn't want to additionally include different approach to testing.

### CODE REVIEW

**Comment by villanuevawill** [comment]
@pgrzesik can you elaborate more on the suggestion? If good, I can put up a bounty for it :)

**Comment by villanuevawill** [comment]
@pgrzesik this looks great. I'm going to pay out the bounty now :)

**Comment by pgrzesik** [comment]
@villanuevawill I'm glad you like it! About the suggestion, it's probably not bounty worthy as it would be pretty small refactor at this point. What I'm suggesting to split one big `tests.py` into smaller modules that have less tests, but specific to e.g. `client_helpers`, it that case, instead of `tests.py`, it would be `tests/test_bounty_client.py` and `tests/test_client_helpers.py`.

Also, there's still a lot of testing to be done for `bounty_client` - and I'm up for that challenge if you'd like :)

**Comment by villanuevawill** [comment]
@pgrzesik the tests are failing.

**Comment by villanuevawill** [comment]
I merged this in/paid out too quickly :/.  But the tests are not working.

**Comment by villanuevawill** [comment]
```
ERROR: Failure: ImportError (cannot import name 'bounty_url_for')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/local/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/local/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/local/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/code/std_bounties/tests.py", line 7, in <module>
    from std_bounties.client_helpers import bounty_url_for, \
ImportError: cannot import name 'bounty_url_for'
```

@pgrzesik you need to rebase master in.

**Comment by pgrzesik** [comment]
@villanuevawill What problems are you experiencing ? Can you show me ? I didn't have any issues and all tests were passing, I will gladly check what's happening and fix it of course

**Comment by villanuevawill** [comment]
@pgrzesik it's because master had moved the location on bounty_url_for

**Comment by pgrzesik** [comment]
Fixed in https://github.com/Bounties-Network/BountiesAPI/pull/57/files, sorry about the issue, I didn't saw anything else merged before submitting my PR

**Comment by pgrzesik** [comment]
@villanuevawill Also, what do you think about enabling CircleCI test jobs for PRs from forks ? It could help prevent such errors in the future.

**Comment by villanuevawill** [comment]
@pgrzesik good idea - I'll set that up now.

Regarding splitting up the tests, great idea.  Also, if you want to keep adding tests I can put another bounty up.

**Comment by pgrzesik** [comment]
@villanuevawill There's still much to test so I'd gladly continue with that task.

**Pull request merged**
