### PR TITLE
[WIP] Bounty API React/Redux Dashboard

### PR DESCRIPTION
**Pull request by bakaoh**
Refs: https://github.com/Bounties-Network/BountiesAPI/issues/23

- [x] Utilizes highcharts or other quick graphing library
- [x] Design is up to the contributor
- [x] Frontend should be an eslint-airbnb compliant React/Redux application
- [x] Bounty states (draft, active, etc.) should be represented by a pie chart
- [x] Remaining stats could go on one line chart with toggles for each
- [x] Perhaps introduce other charts (bar, etc.), or sepearate the average stats into a separate line chart
- [ ] Visualize the full aggregates in addition to the time series data
- [x] Have a dropdown for the page to control the daterange
- [x] Have a dropdown for the page to filter by schema

### CODE REVIEW

**Comment by villanuevawill** [comment]
@bakaoh thanks for the start here (react-create-app).

Can you set this up to use Redux-Sagas please once implementation is moved forward?
What charting library are you thinking of working with?

**Comment by bakaoh** [comment]
@villanuevawill -- it's almost done, you can test it here hhttp://bakaoh.com/BountiesAPI/
since the back-end is not ready, i have add schema 'test' to get dummy data
some of your metric is not clear to me so please let me know if anything wrong

i will submit the work at gitcoin because i've reached the max issues i can work at, please accept it anytime you think it's done

**Comment by villanuevawill** [comment]
@bakaoh - thanks.  I'll go ahead and look at this soon.
Can you rebase or merge in master so the Circle tests run, etc.?

**Comment by villanuevawill** [comment]
@bakaoh so far looking really good... This has moved super quickly.

A couple pieces of feeback...
Rate Bar graph should have the following:
```
fulfillment_acceptance_rate
bounty_fulfilled_rate
avg_fulfiller_acceptance_rate
```

However, these metrics don't add up to 1 - so probably makes more sense just as a line chart.

There should be a separate line chart that includes the following:
```
bounties_issued
fulfillments_submitted
fulfillments_accepted
```

We can get rid of that pie chart...

We should have a sepaerate line chart that includes the following:
```
bounty_draft
bounty_active
bounty_completed
bounty_expired
bounty_dead
```

bounty completed and bounty expired and bounty dead are going to be cumulative, as more and more enter that state over time. Of course, the number around draft and active will rise and drop.

Finally, we shouldn't really need aggregate stats represented. This should be good for now. Additionally, the filter by schema should have an 'All' option as well (meaning no filter applied).

**Comment by villanuevawill** [comment]
@bakaoh  Another pt. of feedback - can you make it more responsive?  As the sidebar is expanded/minimized, the charts don't re-render to fit the width. Any chance you could update that?

Also, I think it makes sense to give the charts a min-width. This allows for a better mobile experience.

**Comment by bakaoh** [comment]
@villanuevawill -- i changed as your requests and rebased to upstream/master
i also moved the menu to top to make more room for the charts

**Comment by villanuevawill** [comment]
@bakaoh lets move this to a new repo. I'm creating it now.

**Comment by villanuevawill** [comment]
@bakaoh git@github.com:Bounties-Network/StdBountiesAnaltyics.git can you open up the PR with readme, etc. in that repo ^^. It's going to be standalone, and the production webpack should have the s3 upload in it. Are you able to sample that?  Also - the actual API should be ready by next week.

**Comment by bakaoh** [comment]
@villanuevawill -- that repo is empty so i can not create a PR

**Comment by bakaoh** [comment]
@villanuevawill -- i don't have permission to push to that repo

**Comment by villanuevawill** [comment]
@bakaoh makes sense. Let me inititalize the repo with an empty readme...

**Comment by villanuevawill** [comment]
@bakaoh it's all ready... Also - can you join the bounties network slack for better communication please? 
bountiesnetwork.slack.com

What issue did you have signing up?

**Comment by bakaoh** [comment]
@villanuevawill i made a pull request https://github.com/Bounties-Network/StdBountiesAnaltyics/pull/1

i don't have slack account, and don't have @bounties.network email address

**Comment by villanuevawill** [comment]
@bakaoh you don't need a bounties.network email.

You just need to sign up for slack. It's free. Do you mind doing that? This is also how you communicate on bounties with gitcoin and the gitcoin community.

**Comment by villanuevawill** [comment]
@bakaoh https://bountiesnetwork.slack.com/join/shared_invite/enQtMzA2Mjk3MzAzODQwLTZjN2UxMmU5MWYxZTVmMmM4OGNjZDRiMDgwYTVhOTIwYmQ4MjVlMjNkZjYzOTE4MWI4OTFhOWE4ZTUzN2MyNWY

To join

**Pull request closed without merging**
