### PR TITLE
Added logic to return deadline entry if platform is gitcoin.

### PR DESCRIPTION
**Pull request by gillichu**

### CODE REVIEW

**Comment by gillichu** [comment]
Why is it failing the CI check?

**Comment by c-o-l-o-r** [comment]
@gillichu we added a Python linter to CI! You'll need to make sure your code is pep8 compliant. Here is what the linter said you needed to fix:

```
./bounties_api/std_bounties/client_helpers.py:51:5: F841 local variable 'meta' is assigned to but never used
./bounties_api/std_bounties/client_helpers.py:71:5: F841 local variable 'bounty' is assigned to but never used
./bounties_api/std_bounties/client_helpers.py:72:10: E126 continuation line over-indented for hanging indent
./bounties_api/std_bounties/client_helpers.py:92:1: E122 continuation line missing indentation or outdented
./bounties_api/std_bounties/client_helpers.py:95:1: E305 expected 2 blank lines after class or function definition, found 1
./bounties_api/std_bounties/client_helpers.py:95:4: F821 undefined name 'metadata'
./bounties_api/std_bounties/client_helpers.py:96:10: E111 indentation is not a multiple of four
./bounties_api/std_bounties/client_helpers.py:96:10: F821 undefined name 'bounty'
./bounties_api/std_bounties/client_helpers.py:96:25: E201 whitespace after '{'
./bounties_api/std_bounties/client_helpers.py:96:65: E202 whitespace before '}'
./bounties_api/std_bounties/client_helpers.py:98:1: F706 'return' outside function
```

**Comment by gillichu** [comment]
I'm failing this test: self.assertEqual(result['platform'], ipfs_data['meta']['platform']) but I'm not really sure why that might be, since I didn't take anything it was already returning, out. I don't know where to find the tests, so should I be returning 'platform' in map_bounty_data as well?

**Comment by c-o-l-o-r** [comment]
Ohh I see the issue. Check your diff--the meta property is getting removed from the return value. Add it back in and that should fix it. @gillichu

**Comment by c-o-l-o-r** [comment]
@gillichu don't forget to define it too 😄

**Comment by gillichu** [comment]
I know, I'm actually the worst. Commit message for every single thing I get wrong. -.- Is there a way to run Python linter locally instead of waiting to see the errors after I push?

**Comment by c-o-l-o-r** [comment]
@gillichu no you're not the worst! I do that so much, I just squash my commits together so no one ever sees 😃 . Yes, there are a couple different ways. You can either run install a linter in your editor to alert you of problems as you code or you could download the linter that is running in CI! It is called flake8. We're running it with these args `flake8 --ignore=E501,F405,W191`.

**Comment by villanuevawill** [comment]
LGTM! Gonna run and test it now.

**Pull request merged**
