### PR TITLE
Add support to code coverage for django and nodejs

### LINKED ISSUE #22: Set up Code Coverage configuration
# Requirements
- Code coverage should be properly configured to cover both the node.js files and the django application.
- Code coverage should be configured properly to run on all required files (management jobs, helpers, etc.)

As an example, code coverage is already setup within the django application. However, the configuration needs to be fixed as it is not covering the right files. To run it, just try `docker-compose exec bounties_api python manage.py test --with-coverage`

# Definition of Done
- All requirements are completed above with the endpoint functional.

# Reviewers
Myself and @mbeylin 

# Review Requirements
- A WIP pull request along the way with initial progress
- Key questions posted here
- Conversational and longer discussions should be directed to the bounties network slack in this channel: https://bountiesnetwork.slack.com/messages/community-dev

### PR DESCRIPTION
**Pull request by zoek1**
## Code coverage with django
```$ docker-compose exec bounties_api python manage.py test```

captura de pantalla de 2018-04-22 02-36-41

## Code coverage with nodejs
```$ docker-compose exec contract_subscriber npm run test```
captura de pantalla de 2018-04-22 02-36-08

Resolve #22

### CODE REVIEW

**Comment by villanuevawill** [comment]
@zoek1 great work - this looks ready.  I'll need to hook this up directly with codecov and circle.

**Comment by villanuevawill** [comment]
But this good to merge in for now?

**Comment by zoek1** [comment]
@villanuevawill I think yes, it will allow to the bounty hunter validate his work with tests and gives you some security about the code is working properly. Also i'm based on this branch to work on #21.

**Comment by villanuevawill** [comment]
@zoek1 great - merging this in now. Today/tomorrow will add circle.

**Pull request merged**
